version: 2.1
orbs:
  node: circleci/node@4.1
  slack: circleci/slack@3.4.2

jobs:
  deploy-to-test-site:  
    docker:
      - image: cimg/python:3.9.6-node
    steps:
      - checkout
      - run: cd app && npm i
      - run: npm dedupe
      - run: cd ../ && git clone git@github.com:supertokens/supertokens-backend-website.git
      - run: curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
      - run: export NVM_DIR="$HOME/.nvm"
      - run: [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      - run: nvm install 16
      - run: nvm use 16 && ./buildJwt
      - run: git config --global user.email "$EMAIL"
      - run: git config --global user.name "$NAME"
      - run: cd ../supertokens-backend-website && git add --all && git commit -m"docs changes" && git push && ./releaseDev.sh
      - slack/status

workflows:
  version: 2
  test:
    jobs:
      - deploy-to-test-site:
          context:
            - slack-notification
          filters:
            branches:
              only:
                - master