version: 2.1
orbs:
  node: circleci/node@4.1
  slack: circleci/slack@3.4.2

jobs:
  deploy-to-test-site:  
    docker:
      - image: cimg/python:3.9.6-node
    steps:
      - checkout
      - node/install-packages:
          app-dir: '~/project/app'
      - run: npm dedupe
      - run: cd ../ && git clone git@github.com:supertokens/supertokens-backend-website.git
      - run: ./buildJwt

      # this makes sure that we don't link to supertokens.io anymore anywhere.
      # Right now, there are exactly 87 instances where we link. If this number needs to 
      # change cause maybe we link to a supertokens.io email (which is valid),
      # then please change the below number to what is expected. 
      - run: (grep -r --exclude-dir={node_modules} "supertokens.io" | wc -l)
      - run: if [[ `(grep -r --exclude-dir={docs,supertokens-backend-website,node_modules} "supertokens.io" | wc -l)` -eq 0 ]]; then exit 0; else exit 1; fi
      - run: git config --global user.email "$EMAIL"
      - run: git config --global user.name "$NAME"
      - run: cd supertokens-backend-website && git add --all && git commit -m"docs changes" && git push && ./releaseDev.sh
      - slack/status

workflows:
  version: 2
  test:
    jobs:
      - deploy-to-test-site:
          context:
            - slack-notification
          filters:
            branches:
              only:
                - master